require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'

# Disable cops for gems we're not using
Capybara/RSpec/PredicateMatcher:
  Enabled: false

RSpec/Capybara:
  Enabled: false

RSpec/FactoryBot:
  Enabled: false

RSpec/Rails:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

# Property tests and integration tests need more flexibility
RSpec/DescribeClass:
  Exclude:
    - 'spec/properties/**/*'
    - 'spec/integration/**/*'

RSpec/ExampleLength:
  Max: 10
  Exclude:
    - 'spec/properties/**/*'
    - 'spec/integration/**/*'

RSpec/MultipleExpectations:
  Max: 5
  Exclude:
    - 'spec/properties/**/*'

RSpec/ExpectActual:
  Exclude:
    - 'spec/properties/**/*'

RSpec/IteratedExpectation:
  Exclude:
    - 'spec/properties/**/*'

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 8

# Parsing methods naturally have higher complexity
Metrics/AbcSize:
  Exclude:
    - 'lib/sales_taxes/services/input_parser.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/sales_taxes/services/input_parser.rb'
    - 'lib/sales_taxes/services/receipt_builder.rb'
